/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:4c8529fe-ae15-4d53-9019-f5bb2f84888f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_YVzrcXf0g",
    "aws_user_pools_web_client_id": "4ihausagra1p7kngkcqge1om3i",
    "oauth": {}
};


export default awsmobile;
